CREATE TABLE cardapio (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(120) NOT NULL UNIQUE,
    descricao VARCHAR(500) NOT NULL,
    preco_unitario DECIMAL(10, 2) NOT NULL
);

CREATE TABLE comanda (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data DATE NOT NULL,
    mesa INT NOT NULL,
    nome_cliente VARCHAR(120) NOT NULL
);

CREATE TABLE comanda_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    comanda_id BIGINT NOT NULL,
    cardapio_id BIGINT NOT NULL,
    quantidade INT NOT NULL,
    CONSTRAINT fk_comanda FOREIGN KEY (comanda_id) REFERENCES comanda (id),
    CONSTRAINT fk_cardapio FOREIGN KEY (cardapio_id) REFERENCES cardapio (id),
    CONSTRAINT uk_comanda_cardapio UNIQUE (comanda_id, cardapio_id)
);
